//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProwin
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CtDonHangs = new HashSet<CtDonHang>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public System.DateTime NgayDH { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public double TongGia { get; set; }
        public string HoNN { get; set; }
        public string TenDemNN { get; set; }
        public string TenNN { get; set; }
        public string DienThoaiNN { get; set; }
        public string DiaChiNN { get; set; }
        public int TrangThai { get; set; }
        public Nullable<int> ThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDonHang> CtDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
