//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProwin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauSac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MauSac()
        {
            this.MaMau_MaKT = new HashSet<MaMau_MaKT>();
        }
    
        public int MaMau { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaLoaiMau { get; set; }
        public string TenMau { get; set; }
        public string Mau { get; set; }
        public Nullable<int> MaAnh { get; set; }
        public string TenFile { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual HinhAnh HinhAnh { get; set; }
        public virtual LoaiMau LoaiMau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaMau_MaKT> MaMau_MaKT { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
