//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProwin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CtDonHangs = new HashSet<CtDonHang>();
            this.MauSacs = new HashSet<MauSac>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaDMC { get; set; }
        public Nullable<int> MaAlbum { get; set; }
        public int MaTH { get; set; }
        public double GiaSP { get; set; }
        public string TenSP { get; set; }
        public string TenSPNU { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> Sale { get; set; }
        public string NoiDung { get; set; }
        public int LuotTruyCap { get; set; }
        public int TrangThai { get; set; }
        public string URL { get; set; }
    
        public virtual Album Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDonHang> CtDonHangs { get; set; }
        public virtual DanhMucCon DanhMucCon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauSac> MauSacs { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
